version: "3"
services:
  postgres:
    image: postgres:12
    # The container port will be available on postgres:5432 to the other services,
    # This is left for easy debugging when needed.
    #    ports:
    #      - 54320:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: raw
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init-postgres/:/docker-entrypoint-initdb.d/:ro

  creds:
    image: ${DOCKER_REGISTRY}/raw-creds-compose:${RAW_VERSION}
    entrypoint: ["/wait-for-it.sh", "postgres:5432", "--", "/opt/docker/bin/raw-creds-compose"]
    # The container port will be available on raw-creds:54322 to the other services,
    # This is left for easy debugging when needed.
    #    ports:
    #      - "54322:54322"
    depends_on:
      - postgres
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh:ro
      - ./etc/raw-common/raw.license:/etc/raw-common/raw.license:ro
      - ./conf/raw-creds/application.conf:/opt/docker/conf/application.conf:ro
      - ./conf/raw-creds/logback.xml:/opt/docker/conf/logback.xml:ro
      - ./conf/auth.conf:/opt/docker/conf/auth.conf:ro
    environment:
      JAVA_OPTS: ${JAVA_OPTS} ${CREDS_JAVA_OPTS}

  storage:
    image: ${DOCKER_REGISTRY}/raw-storage-compose:${RAW_VERSION}
    # The container port will be available on raw-storage:54323 to the other services,
    # This is left for easy debugging when needed.
    #    ports:
    #      - "54323:54323"
    volumes:
      - ./etc/raw-common/raw.license:/etc/raw-common/raw.license:ro
      - ./conf/raw-storage/application.conf:/opt/docker/conf/application.conf:ro
      - ./conf/raw-storage/logback.xml:/opt/docker/conf/logback.xml:ro
      - ./conf/auth.conf:/opt/docker/conf/auth.conf:ro
      - cache:/var/tmp/rawcache
    environment:
      JAVA_OPTS: ${JAVA_OPTS} ${STORAGE_JAVA_OPTS}

  executor:
    image: ${DOCKER_REGISTRY}/raw-executor-compose:${RAW_VERSION}
    entrypoint: ["/wait-for-it.sh", "postgres:5432", "--", "/opt/docker/bin/raw-executor-compose"]
    # So this has to be opened to the web browser directly as it seems some
    # calls are made directly to the executor instead of going through the frontend.
    ports:
      - "${RAW_EXECUTOR_PORT}:54321"
    depends_on:
      - creds
      - postgres
      - storage
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh:ro
      - ./etc/raw-common/raw.license:/etc/raw-common/raw.license:ro
      - ./conf/raw-executor/application.conf:/opt/docker/conf/application.conf:ro
      - ./conf/raw-executor/application.ini:/opt/docker/conf/application.ini:ro
      - ./conf/raw-executor/logback.xml:/opt/docker/conf/logback.xml:ro
      - ./conf/raw-executor/driver-java-options:/opt/docker/conf/driver-java-options:ro
      - ./conf/auth.conf:/opt/docker/conf/auth.conf:ro
      - cache:/var/tmp/rawcache
      - ${RAW_LOGS}:/tmp/raw-driver-logs
      - ${RAW_DATA}:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JAVA_OPTS: ${JAVA_OPTS} ${EXECUTOR_JAVA_OPTS}
      HIVE_VERSION: ${HIVE_VERSION}
      HIVE_HOME: ${HIVE_HOME}
      HDFS_HOSTNAME: ${PUBLIC_ADDRESS}

  frontend:
    image: ${DOCKER_REGISTRY}/raw-frontend-compose:${RAW_VERSION}
    entrypoint: ["/wait-for-it.sh", "postgres:5432", "--", "/opt/docker/bin/raw-frontend-compose"]
    ports:
      - "${RAW_FRONTEND_PORT}:9000"
    depends_on:
      - creds
      - executor
      - postgres
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh:ro
      - ./etc/raw-common/raw.license:/etc/raw-common/raw.license:ro
      - ./conf/raw-frontend/application.conf:/opt/docker/conf/application.conf:ro
      - ./conf/raw-frontend/logback.xml:/opt/docker/conf/logback.xml:ro
      - ./conf/auth.conf:/opt/docker/conf/auth.conf:ro
    environment:
      JAVA_OPTS: ${JAVA_OPTS} ${FRONTEND_JAVA_OPTS}
      PUBLIC_ADDRESS: ${PUBLIC_ADDRESS}
      RAW_EXECUTOR_PORT: ${RAW_EXECUTOR_PORT}

volumes:
  postgres:
  cache:

