version: "3"
services:
  postgres:
    image: postgres:12
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: raw
    volumes:
      - raw_postgres:/var/lib/postgresql/data
      - ./init-postgres/:/docker-entrypoint-initdb.d/

  raw-creds:
    image: ${DOCKER_REGISTRY}/raw-creds-compose:${RAW_VERSION}
    entrypoint: ["/wait-for-it.sh", "postgres:5432", "--", "/opt/docker/bin/raw-creds-compose"]
    ports:
      - "54322:54322"
    depends_on:
      - postgres
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh:ro
      - ./etc/raw-common/raw.license:/etc/raw-common/raw.license:ro
      - ./conf/raw-creds/application.conf:/opt/docker/conf/application.conf:ro
      - ./conf/raw-creds/logback.xml:/opt/docker/conf/logback.xml:ro
      - ./conf/auth.conf:/opt/docker/conf/auth.conf:ro
    environment:
      JAVA_OPTS: ${JAVA_OPTS} ${CREDS_JAVA_OPTS}

  raw-storage:
    image: ${DOCKER_REGISTRY}/raw-storage-compose:${RAW_VERSION}
    ports:
      - "54323:54323"
    volumes:
      - ./etc/raw-common/raw.license:/etc/raw-common/raw.license:ro
      - ./conf/raw-storage/application.conf:/opt/docker/conf/application.conf:ro
      - ./conf/raw-storage/logback.xml:/opt/docker/conf/logback.xml:ro
      - ./conf/auth.conf:/opt/docker/conf/auth.conf:ro
      - raw_cache:/var/tmp/rawcache

    environment:
      JAVA_OPTS: ${JAVA_OPTS} ${STORAGE_JAVA_OPTS}

  raw-executor:
    image: ${DOCKER_REGISTRY}/raw-executor-compose:${RAW_VERSION}
    entrypoint: ["/wait-for-it.sh", "postgres:5432", "--", "/opt/docker/bin/raw-executor-compose"]
    ports:
      - "54321:54321"
    depends_on:
      - raw-creds
      - postgres
      - raw-storage
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh:ro
      - ./etc/raw-common/raw.license:/etc/raw-common/raw.license:ro
      - ./conf/raw-executor/application.conf:/opt/docker/conf/application.conf:ro
      - ./conf/raw-executor/application.ini:/opt/docker/conf/application.ini:ro
      - ./conf/raw-executor/logback.xml:/opt/docker/conf/logback.xml:ro
      - ./conf/raw-executor/driver-java-options:/opt/docker/conf/driver-java-options:ro
      - ./conf/auth.conf:/opt/docker/conf/auth.conf:ro
      - raw_cache:/var/tmp/rawcache
      - /tmp/raw-driver-logs:/tmp/raw-driver-logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JAVA_OPTS: ${JAVA_OPTS} ${EXECUTOR_JAVA_OPTS}
      HIVE_VERSION: ${HIVE_VERSION}
      HIVE_HOME: ${HIVE_HOME}
      HDFS_HOSTNAME: ${PUBLIC_ADDRESS}

  raw-frontend:
    image: ${DOCKER_REGISTRY}/raw-frontend-compose:${RAW_VERSION}
    entrypoint: ["/wait-for-it.sh", "postgres:5432", "--", "/opt/docker/bin/raw-frontend-compose"]
    ports:
      - "9000:9000"
    depends_on:
      - raw-creds
      - raw-executor
      - postgres
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh:ro
      - ./etc/raw-common/raw.license:/etc/raw-common/raw.license:ro
      - ./conf/raw-frontend/application.conf:/opt/docker/conf/application.conf:ro
      - ./conf/raw-frontend/logback.xml:/opt/docker/conf/logback.xml:ro
      - ./conf/auth.conf:/opt/docker/conf/auth.conf:ro
    environment:
      JAVA_OPTS: ${JAVA_OPTS} ${FRONTEND_JAVA_OPTS}
      PUBLIC_ADDRESS: ${PUBLIC_ADDRESS}

volumes:
  raw_postgres:
  raw_cache:
    external: true
